name: Go
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go
      
    - name: Set up protoc
      uses: arduino/setup-protoc@v1.1.0
      
    - name: Set up protoc go plugins
      run: go get github.com/micro/protoc-gen-micro; go get github.com/golang/protobuf/protoc-gen-go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Build
      run: make
